export const CHANGE_CHECK_STATUS = 'CHANGE_CHECK_STATUS';
export const SET_USER_IMAGE = 'SET_USER_IMAGE';
export const CHANGE_USER_LOCATION = 'CHANGE_USER_LOCATION';
export const ON_DATE_UPDATE = 'ON_DATE_UPDATE';
export const ON_ODOMETER_UPDATE = 'ON_ODOMETER_UPDATE';